### ISSUE TITLE
Assert_equal nil, should be Assert_nil

### ISSUE THREAD

**Issue by GeorgieGirl24** [turingschool/ruby-exercises#75]
Re: enumerables/exercises_1/find_pattern_test.rb

<img width="801" alt="Screen Shot 2020-07-16 at 12 12 20 PM" src="https://user-images.githubusercontent.com/62966396/87716602-4ec2b500-c76c-11ea-994d-a9b681e01d8c.png">

I recently found that working through the exercise, the pass of a Mintiest was followed by a prompt about a future fail in an upcoming version of Mintiest. Mintiest was requesting `assert_nil nil` instead of `assert_equal nil`

**Comment by josh-works** [comment]
Hi @GeorgieGirl24, thanks for filing this!

Sure enough, `assert_equal nil, actual` is deprecated in favor of [`assert_nil, actual`](http://docs.seattlerb.org/minitest/Minitest/Assertions.html#method-i-assert_nil)

You mentioned that you've made a commit to fix the problem, swapping out the offending assertions. 

Lets talk through getting the pull request made! 

Here's the steps I think you'll need to take. Can you give them a shot, let me know where I forget to mention something?

1. fork this ruby-exercises repository to your own github account. 
2. attach your local version of the ruby-exercises directory to your forked github repository. Something like:

```
$ git remote add origin <url-to-your-forked-github-repo>
```
should do it.

3. Check out a new branch, `git checkout -b fix-assert-equal-nil`
4. Push the new branch to your forked repository: `git push origin fix-assert-equal-nil`
5. create a new pull request from your forked repository to this repository.

There's plenty of complexity in these above steps - I'm 100% happy to help coach you through it. As much as possible, I want to keep the instructions here in public so future students can find this knowledge.
